#!/bin/bash
#
make uninstall; make clean; make distclean;
#
#
\rm -f $HOME/local/install/SPH/include/* 
\rm -f $HOME/local/install/SPH/bin/sph
\rm -f $HOME/local/install/SPH/lib/*
#
#
./bootstrap         |& tee /tmp/sph_config_make.log
#
#
#
./configure --prefix=$HOME/local/install/SPH \
     CFLAGS="-ggdb -D_FILE_OFFSET_BITS=64" \
     CPPFLAGS="-I/usr/local/ann_1.1.2/include -I/usr/local/ann_1.1.2/include/ANN -Wall" \
     CXXFLAGS="-ggdb" \
     LDFLAGS="-L/usr/local/ann_1.1.2/lib -lANN -lm -lpthread" \
     --enable-shared=no \
     --with-pic \
     --with-mpi=yes |& tee /tmp/sph_config_make.log
#
make -j4            |& tee /tmp/sph_config_make.log
#
make install        |& tee /tmp/sph_config_make.log
#
#cp $PWD/par/sph.par       $HOME/local/install/SPH/par
#cp $PWD/src/scripts/bobs  $HOME/local/install/SPH/bin
#cp $PWD/src/machines      $HOME/local/install/SPH
#
