#!/bin/sh
#
make uninstall; make clean; make distclean;
#
#
\rm -f $HOME/local/install/SPH/include/* 
\rm -f $HOME/local/install/SPH/bin/sph
\rm -f $HOME/local/install/SPH/lib/*
#
#
./bootstrap
#
#
#
echo "Calling configure: " >> /tmp/junk.txt
./configure --prefix=$HOME/local/install/SPH \
     CFLAGS="-ggdb -D_FILE_OFFSET_BITS=64" \
     CPPFLAGS="-I/usr/local/ann_1.1.2/include -I/usr/local/ann_1.1.2/include/ANN -Wall" \
     CXXFLAGS="-ggdb" \
     LDFLAGS="-L/usr/local/ann_1.1.2/lib -lANN -lm -lpthread" \
     --enable-shared=no \
     --with-pic \
     --with-mpi=yes
#
echo "Calling make: " >> /tmp/junk.txt
make -j4
#
echo "Calling make install: " >> /tmp/junk.txt
make install
#
#cp $PWD/par/sph.par       $HOME/local/install/SPH/par
#cp $PWD/src/scripts/bobs  $HOME/local/install/SPH/bin
#cp $PWD/src/machines      $HOME/local/install/SPH
#
