#!/bin/sh
#
make uninstall; make clean; make distclean;
#
#
\rm -f $HOME/local/install/SPH/include/* 
\rm -f $HOME/local/install/SPH/bin/sph
\rm -f $HOME/local/install/SPH/lib/*
#
#
./bootstrap
#
#
#
./configure --prefix=$HOME/local/install/SPH \
     CFLAGS="-ggdb -D_FILE_OFFSET_BITS=64" \
     CPPFLAGS="-I$HOME/local/ann_1.1.2/include -I$HOME/local/ann_1.1.2/include/ANN -Wall" \
     CXXFLAGS="-ggdb" \
     LDFLAGS="-L$HOME/local/ann_1.1.2/lib -lANN -lm -lpthread" \
     --enable-shared=no \
     --with-pic \
     --with-mpi=yes
#
make -j4
#
make install
#
cp $PWD/par/sph.par       $HOME/local/install/SPH/par
cp $PWD/src/scripts/bobs  $HOME/local/install/SPH/bin
cp $PWD/src/machines      $HOME/local/install/SPH
#
