  if ( (((ALPHA=pars[0].ALPHA)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((GAMMA=pars[0].GAMMA)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((BETA=pars[0].BETA)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((ETA=pars[0].ETA)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((EPSILON=pars[0].EPSILON)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((G1=pars[0].G1)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((G2=pars[0].G2)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((D=pars[0].D)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((H0=pars[0].H0)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       (((NN_EPS=pars[0].NN_EPS)-LARGE_NEGATIVE_DOUBLE)<EPSILON_FLOAT)
                              ||
       ((KERNEL_ID=pars[0].KERNEL_ID)==LARGE_NEGATIVE_INT)
                              ||
       ((DIMENSIONS=pars[0].DIMENSIONS)==LARGE_NEGATIVE_INT)
                              ||
       ((PARTICLES_IN_X=pars[0].PARTICLES_IN_X)==LARGE_NEGATIVE_INT)
                              ||
       ((PARTICLES_IN_Y=pars[0].PARTICLES_IN_Y)==LARGE_NEGATIVE_INT)
                              ||
       ((PARTICLES_IN_Z=pars[0].PARTICLES_IN_Z)==LARGE_NEGATIVE_INT)
                              ||
       ((NN_k=pars[0].NN_k)==LARGE_NEGATIVE_INT)
                              ||
       ((ZERO=pars[0].ZERO)==LARGE_NEGATIVE_INT)
                              ||
       ((CENTRE_POINT=pars[0].CENTRE_POINT)==LARGE_NEGATIVE_INT)
                              ||
       ((EXTRA=pars[0].EXTRA)==LARGE_NEGATIVE_INT)
                              ||
       ((OFFSET=pars[0].OFFSET)==LARGE_NEGATIVE_INT)
                              ||
       ((RESTART=pars[0].RESTART)==LARGE_NEGATIVE_INT)
       
